# Generated by Django 5.0.7 on 2024-07-27 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SteamSearcher',
            fields=[
                ('appid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('detailed_description', models.TextField()),
                ('recommendation_count', models.FloatField()),
                ('type', models.CharField(max_length=255)),
                ('developer', models.CharField(max_length=255)),
                ('release_date', models.TextField()),
                ('keyphrase', models.CharField(max_length=255)),
                ('summary', models.CharField(max_length=1024)),
                ('description_phrases', models.JSONField()),
            ],
            options={
                'db_table': 'steamsearcher_duplicate',
            },
        ),
    ]
