# Generated by Django 5.0.7 on 2024-07-23 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SteamSearcher',
            fields=[
                ('appid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('detailed_description', models.TextField()),
                ('recommendation_count', models.FloatField()),
                ('type', models.CharField(max_length=255)),
                ('developer', models.CharField(max_length=255)),
                ('release_date', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
