# Generated by Django 5.0.7 on 2024-07-23 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_steamsearcher_delete_testmodel'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='steamsearcher',
            table='steamsearcher',
        ),
    ]
