# Generated by Django 5.0.7 on 2024-07-24 00:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_alter_steamsearcher_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='steamsearcher',
            name='keyphrase',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='steamsearcher',
            name='summary',
            field=models.TextField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
