# Generated by Django 5.0.7 on 2024-07-24 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_steamsearcher_keyphrase_steamsearcher_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steamsearcher',
            name='summary',
            field=models.CharField(max_length=1024),
        ),
    ]
