# Generated by Django 5.0.7 on 2024-07-24 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_alter_steamsearcher_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='steamsearcher',
            name='image_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
