# Generated by Django 5.0.7 on 2024-07-24 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_steamsearcher_image_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='steamsearcher',
            name='image_filename',
        ),
    ]
